# Jykell configuration
#markdown: redcarpet
#highlighter: pygments
#encoding: UTF-8
markdown: kramdown
highlighter: rouge
paginate: 5
language: 'de-de'

# Website info
name: 'Evang. Kinderkirche Möglingen Süd'
description: ""

# Author's info
author: 'Kinderkirche'
# edit 'categories' in the front matter of every post to match this username
nickname: Kiki
bio: '-'
location: 'Möglingen, Deutschland'
url: 'http://kiki-moeglingen.github.io'
image: 'assets/images/kiki-logo-100.png'

short_url: 'kiki-moeglingen.github.io'
google_analytics: UA-69281367-1
disqus: username
# edit baseurl to simply '/' if using as your personal page (instead of a project page)
baseurl: /

# Permalinks
permalink: /:title
# permalink: /author/:username
# permalink: /tag/:tag


# gems and other configs
gems: [jekyll-paginate]
exclude: [vendor]

# Additional settings available on the front-matter
# Site logo in the index.html (as in demo.ghost.io)
# Author's page cover in _layouts/author.html
# The same for page.html and tag.html layouts
# Post's page cover as a per-post basis _posts/...
# Disqus comments as a per-post basis
# ...


# Settings for builing master branch with travis-ci
# with jekyll-travis

# Settings for deploy rake task
# Username and repo of Github repo, e.g.
# https://github.com/USERNAME/REPO.git
# username defaults to ENV['GIT_NAME'] used by Travis
# repo defaults to USERNAME.github.io
# Branch defaults to "source" for USERNAME.github.io
# or "master" otherwise
safe: false
lsi: false
username: kiki-moeglingen
repo: kiki-moeglingen.github.io
branch: master
relative_source: ../kiki-moeglingen.github.io/
destination: ../kiki-moeglingen-pages/
production_url:  https://kiki-moeglingen.github.io
source_url:      https://github.com/kiki-moeglingen/kiki-moeglingen.github.io

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml
